/*
 Navicat Premium Data Transfer

 Source Server         : DiscordBot
 Source Server Type    : PostgreSQL
 Source Server Version : 160008
 Source Host           : dpg-cv0n8k1opnds73ddi1qg-a.singapore-postgres.render.com:5432
 Source Catalog        : discordbot_y4ce
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160008
 File Encoding         : 65001

 Date: 28/04/2025 18:24:30
*/


-- ----------------------------
-- Table structure for __EFMigrationsHistory
-- ----------------------------
DROP TABLE IF EXISTS "public"."__EFMigrationsHistory";
CREATE TABLE "public"."__EFMigrationsHistory" (
  "MigrationId" "pg_catalog"."varchar" COLLATE "pg_catalog"."default" NOT NULL,
  "ProductVersion" "pg_catalog"."varchar" COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of __EFMigrationsHistory
-- ----------------------------
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250228211539_InitialCreate', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250301140715_DiscordRoleChannelCreate', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250301171847_FixMigrations', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250301182224_UpdateDiscordRoles', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250309091402_AddMessageTypeToMonitoredMessage', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250310161406_AddGuildMemberAndOneLineBond', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250310163717_AddGuildMemberStatistics', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250310170824_RemoveGuildMemberId', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250310172002_AddNickName', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250310175850_AddStatisticsConfig', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250310182454_RemoveMemberStatisticsId', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250310182617_RemoveMemberStatisticsIds', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250310182930_AddStatisticsConfigName', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250315061255_UpdatePartnerIdType', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250315082837_Fix_DiscordId_Type', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250315100212_AddOneLineBondName', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250328144650_AddGuildMemberUpdateTime', '9.0.2');
INSERT INTO "public"."__EFMigrationsHistory" VALUES ('20250401224139_CreateGuildTeams', '9.0.2');

-- ----------------------------
-- Table structure for DiscordChannels
-- ----------------------------
DROP TABLE IF EXISTS "public"."DiscordChannels";
CREATE TABLE "public"."DiscordChannels" (
  "Id" "pg_catalog"."numeric" NOT NULL,
  "ChannelName" "pg_catalog"."text" COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of DiscordChannels
-- ----------------------------
INSERT INTO "public"."DiscordChannels" VALUES (1345452585103921282, '꒰👥꒱〢身份組認領');
INSERT INTO "public"."DiscordChannels" VALUES (1348231963898679296, '꒰📊꒱〢統計專區');

-- ----------------------------
-- Table structure for DiscordMessages
-- ----------------------------
DROP TABLE IF EXISTS "public"."DiscordMessages";
CREATE TABLE "public"."DiscordMessages" (
  "Id" "pg_catalog"."int4" NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "ChannelId" "pg_catalog"."numeric" NOT NULL,
  "Content" "pg_catalog"."text" COLLATE "pg_catalog"."default" NOT NULL,
  "Type" "pg_catalog"."int4" NOT NULL,
  "CreatedAt" "pg_catalog"."timestamptz" NOT NULL DEFAULT now(),
  "UpdateAt" "pg_catalog"."timestamptz" NOT NULL
)
;

-- ----------------------------
-- Records of DiscordMessages
-- ----------------------------
INSERT INTO "public"."DiscordMessages" VALUES (2, 1335802137443045376, '<@&1335798409688518657>大家安安，等等8點有幫會戰，請大家踴躍參加 🤩', 3, '2025-03-01 00:53:32.348486+00', '2025-03-01 00:53:32.348486+00');
INSERT INTO "public"."DiscordMessages" VALUES (1, 1335802137443045376, '<@&1335798409688518657>大家安安，今天晚上8點有幫會戰，請大家踴躍參加 🤩', 3, '2025-02-28 23:39:52.575102+00', '2025-02-28 23:39:52.575102+00');
INSERT INTO "public"."DiscordMessages" VALUES (3, 1335802137443045376, '<@&1335798409688518657>還沒進DC幫戰頻道的人記得進來聽指揮歐 🤩', 3, '2025-03-01 01:02:17.929064+00', '2025-03-01 01:02:17.929064+00');
INSERT INTO "public"."DiscordMessages" VALUES (4, 1335803316659032118, '測試用訊息', 0, '2025-03-01 11:22:48.292014+00', '2025-03-01 11:22:48.292014+00');

-- ----------------------------
-- Table structure for DiscordRoles
-- ----------------------------
DROP TABLE IF EXISTS "public"."DiscordRoles";
CREATE TABLE "public"."DiscordRoles" (
  "Id" "pg_catalog"."numeric" NOT NULL,
  "RoleName" "pg_catalog"."text" COLLATE "pg_catalog"."default" NOT NULL,
  "DiscordRoleType" "pg_catalog"."int4" NOT NULL DEFAULT 0
)
;

-- ----------------------------
-- Records of DiscordRoles
-- ----------------------------
INSERT INTO "public"."DiscordRoles" VALUES (1343254054679351356, '𓇻．柔霧粉', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343257439134421033, '𓇻．玫瑰粉', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1344000928537251851, '𓇻．女團粉', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343259625038020761, '𓇻．草莓奶霜', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343259151651962963, '𓇻．焦糖杏仁', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343948660731281439, '𓇻．柳橙橘', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343260172524585010, '𓇻．薰衣草', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343949670896111627, '𓇻．芋頭紫', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343949154367307868, '𓇻．紫羅蘭', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343258592572215378, '𓇻．碧湖藍', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343949664117985290, '𓇻．霧藍', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343950161407115264, '𓇻．蔚藍', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343258517280129055, '𓇻．海洋之星', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343259496713027585, '𓇻．抹茶奶霜', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343258841671929946, '𓇻．松花青', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343952020083576842, '𓇻．經典綠', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343952874278879232, '𓇻．墨綠', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343953205897465977, '𓇻．鮮黃', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343256277538574438, '𓇻．奶油黃', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1343258062106136586, '𓇻．白巧克力', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1344351623060914216, '𓇻．藍莓牛奶', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1344358121572667433, '𓇻．灰茶', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1344358499207090186, '𓇻．純白', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1344358873225625600, '𓇻．向日葵', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1344359212633034812, '𓇻．金赤', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1344367811945828494, '𓇻．塔塔色', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1344373261336580306, '𓇻．草莓蛋糕', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1344373524944519219, '𓇻．草莓布蕾', 0);
INSERT INTO "public"."DiscordRoles" VALUES (1345481853209149450, '⚔．𝟑𝘃𝟑霸主', 1);
INSERT INTO "public"."DiscordRoles" VALUES (1345483299119825001, '⚔．𝟏𝟐𝘃𝟏𝟐鬥神', 1);
INSERT INTO "public"."DiscordRoles" VALUES (1345484264552136734, '⚔．逐鹿仙原武尊', 1);
INSERT INTO "public"."DiscordRoles" VALUES (1348626031669411872, '⚔．緝盜小隊', 1);
INSERT INTO "public"."DiscordRoles" VALUES (1335803592401092628, '☪︎．神相', 2);
INSERT INTO "public"."DiscordRoles" VALUES (1335803907808432149, '☪︎．素問', 2);
INSERT INTO "public"."DiscordRoles" VALUES (1335803758264844398, '☪︎．鐵衣', 2);
INSERT INTO "public"."DiscordRoles" VALUES (1335803510914023556, '☪︎．九靈', 2);
INSERT INTO "public"."DiscordRoles" VALUES (1335804037466947657, '☪︎．碎夢', 2);
INSERT INTO "public"."DiscordRoles" VALUES (1335803662332727329, '☪︎．血河', 2);
INSERT INTO "public"."DiscordRoles" VALUES (1354475906621640777, '☪︎．龍吟', 2);

-- ----------------------------
-- Table structure for GuildMembers
-- ----------------------------
DROP TABLE IF EXISTS "public"."GuildMembers";
CREATE TABLE "public"."GuildMembers" (
  "DiscordId" "pg_catalog"."int8" NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "DiscordName" "pg_catalog"."text" COLLATE "pg_catalog"."default" NOT NULL,
  "CharacterClass" "pg_catalog"."int4",
  "JoinDate" "pg_catalog"."timestamptz" NOT NULL DEFAULT now(),
  "MemberName" "pg_catalog"."text" COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text,
  "UpdateTime" "pg_catalog"."timestamptz"
)
;

-- ----------------------------
-- Records of GuildMembers
-- ----------------------------
INSERT INTO "public"."GuildMembers" VALUES (112543801976893440, 'jason508#0000', 0, '2025-04-02 00:02:36.674229+00', '夫人傾國傾城', NULL);
INSERT INTO "public"."GuildMembers" VALUES (163231110443171840, 'musck_#0000', 2, '2025-04-02 00:03:13.529358+00', '花火繚亂', NULL);
INSERT INTO "public"."GuildMembers" VALUES (277859742830034944, 'jjy0605#0000', 2, '2025-04-02 00:02:29.133337+00', '搖到外婆橋', NULL);
INSERT INTO "public"."GuildMembers" VALUES (315387095130832897, 'shaorun#0000', 4, '2025-04-02 00:02:57.910641+00', '篠雨宮', NULL);
INSERT INTO "public"."GuildMembers" VALUES (326695675741995015, 'onyx_0418#0000', 1, '2025-04-02 00:03:02.171887+00', '我老公', NULL);
INSERT INTO "public"."GuildMembers" VALUES (334291140851269632, 't10055089#0000', 1, '2025-04-02 00:03:03.825104+00', '花語焉', NULL);
INSERT INTO "public"."GuildMembers" VALUES (337976161009139712, 'joki1763#0000', 0, '2025-04-02 00:02:37.35186+00', '瀀初', NULL);
INSERT INTO "public"."GuildMembers" VALUES (355332247504814081, 'sk_zy#0000', 1, '2025-04-02 00:03:16.488448+00', '漓笙笙', NULL);
INSERT INTO "public"."GuildMembers" VALUES (356848603442053130, 'william3510#0000', 2, '2025-04-02 00:02:52.287898+00', '艮嶽', NULL);
INSERT INTO "public"."GuildMembers" VALUES (391561628975497218, 'lntin#0000', 2, '2025-04-02 00:02:59.912623+00', '神凜幻域', NULL);
INSERT INTO "public"."GuildMembers" VALUES (396651117532020746, 'gggary#0000', 4, '2025-04-02 00:02:32.917036+00', '百里獨行丶', NULL);
INSERT INTO "public"."GuildMembers" VALUES (409351484854239233, 'usagi_1209#0000', 0, '2025-04-02 00:02:53.611663+00', '櫻玥兔', NULL);
INSERT INTO "public"."GuildMembers" VALUES (418038803018678321, 'zhangergou5234#0000', 2, '2025-04-02 00:03:12.922759+00', '壹柒伍', NULL);
INSERT INTO "public"."GuildMembers" VALUES (472397644279447552, 'xiaoyi0180#0000', 0, '2025-04-02 00:02:29.74574+00', '夜小伊', NULL);
INSERT INTO "public"."GuildMembers" VALUES (476305034448076811, 'zongyuan.#0000', 4, '2025-04-02 00:02:34.797843+00', '蹤影', NULL);
INSERT INTO "public"."GuildMembers" VALUES (498868109818593300, 'cutecat0530#0000', 1, '2025-04-02 00:02:42.071376+00', '笭雪喵', NULL);
INSERT INTO "public"."GuildMembers" VALUES (505686653197746186, 'little_meowww#0000', 1, '2025-04-02 00:02:50.04691+00', '小貓兒', NULL);
INSERT INTO "public"."GuildMembers" VALUES (520222167481319424, 'ying.8877_#0000', 3, '2025-04-02 00:03:07.380583+00', '魃魑', NULL);
INSERT INTO "public"."GuildMembers" VALUES (524557540621680640, 'mathshark_#0000', 2, '2025-04-02 00:03:08.328419+00', '藥入花眠鎖夜夢', NULL);
INSERT INTO "public"."GuildMembers" VALUES (525720558521024514, '02150620#0000', 3, '2025-04-02 00:02:54.953793+00', '大家安安', NULL);
INSERT INTO "public"."GuildMembers" VALUES (557928446559387659, '2catcodile#0000', 3, '2025-04-02 00:02:48.511876+00', '青燈倚窗盼君歸', NULL);
INSERT INTO "public"."GuildMembers" VALUES (558310783516278794, 'xuan6666#0000', 3, '2025-04-02 00:02:45.877351+00', '殘雪久未融', NULL);
INSERT INTO "public"."GuildMembers" VALUES (564378682429276180, '_amatsukanav.#0000', 3, '2025-04-02 00:02:40.640757+00', '林栖', NULL);
INSERT INTO "public"."GuildMembers" VALUES (661916530774245377, '_alan0416#0000', 2, '2025-04-02 00:02:57.275756+00', '陳逍', NULL);
INSERT INTO "public"."GuildMembers" VALUES (744474458009370644, 'slaaaash.#0000', 5, '2025-04-02 00:02:55.982322+00', '擇輪司機', NULL);
INSERT INTO "public"."GuildMembers" VALUES (766938163875938324, 'hr._.628496#0000', 1, '2025-04-02 00:03:17.751005+00', '舒窈', NULL);
INSERT INTO "public"."GuildMembers" VALUES (783351681915158548, 'youzaku#0000', 1, '2025-04-02 00:02:54.226765+00', '琳琅', NULL);
INSERT INTO "public"."GuildMembers" VALUES (824165263272312852, 'lita1118#0000', 1, '2025-04-02 00:02:42.6825+00', '長離', NULL);
INSERT INTO "public"."GuildMembers" VALUES (857421612281888779, 'bagel.tsai#0000', 1, '2025-04-02 00:02:51.686227+00', '爾冬寬寬', NULL);
INSERT INTO "public"."GuildMembers" VALUES (891856852432863243, 'someone_7269#0000', 1, '2025-04-02 00:02:33.559432+00', '語柔', NULL);
INSERT INTO "public"."GuildMembers" VALUES (909878300632031262, 'haruka_qq#0000', 1, '2025-04-02 00:02:58.60123+00', '櫻桃小魚丸', NULL);
INSERT INTO "public"."GuildMembers" VALUES (967483737468186714, 'paul_lyc#0000', 0, '2025-04-02 00:03:15.486363+00', '思欲返宸', NULL);
INSERT INTO "public"."GuildMembers" VALUES (982308718484004925, '_na_bi#0000', 1, '2025-04-02 00:02:36.088624+00', '逸筱菲', NULL);
INSERT INTO "public"."GuildMembers" VALUES (1017432363434791034, 'raineric#0000', 2, '2025-04-02 00:02:52.95558+00', '花雨紛飛陌相思', NULL);
INSERT INTO "public"."GuildMembers" VALUES (1083333926145232946, 'yaoyao07192#0000', 3, '2025-04-02 00:02:46.590774+00', '瞳紫夜宸', NULL);
INSERT INTO "public"."GuildMembers" VALUES (472440976758276097, 'shps9804#0000', 1, '2025-04-02 00:02:39.053529+00', '墨梓璿', '2025-04-02 02:08:44.218297+00');
INSERT INTO "public"."GuildMembers" VALUES (181297590388654080, 'kunsun#0000', 6, '2025-04-02 00:02:49.12963+00', '擒無邊光斷天命', '2025-04-02 06:28:09.925522+00');
INSERT INTO "public"."GuildMembers" VALUES (316650845410426893, 'yuhao3274#0000', 6, '2025-04-02 00:03:05.35896+00', '蘇宇豪', '2025-04-02 06:28:11.857611+00');
INSERT INTO "public"."GuildMembers" VALUES (352084105657319425, 'ovv1127#0000', 1, '2025-04-02 00:03:14.80251+00', '襄逸', '2025-04-02 06:28:12.573254+00');
INSERT INTO "public"."GuildMembers" VALUES (433453802272849920, 'm3_5ya#0000', 6, '2025-04-20 07:26:44.335336+00', '上古丶地狼舞夜', '2025-04-20 10:29:14.82888+00');
INSERT INTO "public"."GuildMembers" VALUES (1008084653544046593, 'qianqianouob#0000', 3, '2025-04-02 00:02:44.790267+00', '夫君威震八方', '2025-04-10 09:46:48.420913+00');
INSERT INTO "public"."GuildMembers" VALUES (562270564220272670, 'maoyao7741#0000', 2, '2025-04-20 10:29:15.788877+00', '上古丶玄武幽冥', NULL);
INSERT INTO "public"."GuildMembers" VALUES (823391830288629800, 'starwy1030#0000', 6, '2025-04-02 00:03:03.109827+00', '拾星', '2025-04-02 06:28:09.282689+00');
INSERT INTO "public"."GuildMembers" VALUES (1076134921141244044, '._.tana._.#0000', 1, '2025-04-02 00:02:41.334274+00', '海棠微雨梨花雪', '2025-04-27 09:06:58.660168+00');
INSERT INTO "public"."GuildMembers" VALUES (501759556544888844, 'g8pongou#0000', 3, '2025-04-02 00:02:28.221697+00', '瀧雨', '2025-04-02 15:22:44.886493+00');
INSERT INTO "public"."GuildMembers" VALUES (690261526132686916, 'gcobs1008#0000', 3, '2025-04-02 00:02:43.603482+00', '汐雨', '2025-04-02 15:22:49.837823+00');
INSERT INTO "public"."GuildMembers" VALUES (574918160197746699, 'hi_jia#0000', 0, '2025-04-20 10:29:13.811482+00', '上古丶九嬰恋羽', NULL);
INSERT INTO "public"."GuildMembers" VALUES (686879184059891715, 'dongdong2326#0000', 6, '2025-04-02 00:02:30.365573+00', '染銀凌', '2025-04-04 01:25:51.881721+00');
INSERT INTO "public"."GuildMembers" VALUES (576804780584861706, '251_k#0000', 3, '2025-04-20 10:29:09.056129+00', '上古丶奎蛇龍逸', NULL);
INSERT INTO "public"."GuildMembers" VALUES (948733226426458162, 'zhezhi01#0000', 2, '2025-04-05 09:21:48.876746+00', '柳如烟', NULL);
INSERT INTO "public"."GuildMembers" VALUES (272377247938117632, 'a00822007#0000', 3, '2025-04-02 00:03:04.447248+00', '炯熾', '2025-04-05 15:43:13.7376+00');
INSERT INTO "public"."GuildMembers" VALUES (1353033269343555598, 'mq_123_10680#0000', 2, '2025-04-05 15:43:09.258973+00', '扶老爺爺過肩摔', NULL);
INSERT INTO "public"."GuildMembers" VALUES (550326920181448710, 'yua3473#0000', 3, '2025-04-02 00:03:01.128418+00', '三十歲美艷后媽', '2025-04-08 14:31:05.614418+00');
INSERT INTO "public"."GuildMembers" VALUES (247054516237631490, 'gzzzz12#0000', 2, '2025-04-08 14:31:13.804947+00', '超級街頭霸王', NULL);
INSERT INTO "public"."GuildMembers" VALUES (381399468655902720, 'jfla_lyneisha#0000', 5, '2025-04-08 14:31:10.133076+00', '沈詩青', NULL);
INSERT INTO "public"."GuildMembers" VALUES (525692851468763156, 'xiaoxie1113#0000', 4, '2025-04-20 13:51:23.453159+00', '赫墨拉', NULL);
INSERT INTO "public"."GuildMembers" VALUES (995160471185408112, 'ccindy_linnnn#0000', 0, '2025-04-10 09:46:42.525022+00', '青朔', NULL);
INSERT INTO "public"."GuildMembers" VALUES (582127945670197256, 'muzi0600#0000', 4, '2025-04-02 00:03:00.520971+00', '白衣沽酒', '2025-04-10 09:49:14.037347+00');
INSERT INTO "public"."GuildMembers" VALUES (546543160055300127, '_gulong_#0000', 4, '2025-04-15 10:36:08.860203+00', '蠱龍', NULL);
INSERT INTO "public"."GuildMembers" VALUES (1308436623456862208, 'ceshi1230459#0000', 0, '2025-04-02 00:03:10.684367+00', '白茶許語', '2025-04-18 11:09:52.121448+00');
INSERT INTO "public"."GuildMembers" VALUES (699094304915980318, 'a0983608155#0000', 6, '2025-04-18 11:09:56.215227+00', '不羡龍吟', NULL);
INSERT INTO "public"."GuildMembers" VALUES (1339598641848913980, 's1011011#0000', 1, '2025-04-18 11:09:52.443613+00', '雨露夢雪', NULL);
INSERT INTO "public"."GuildMembers" VALUES (334349689061113856, 'midori0809#0000', 3, '2025-04-20 07:26:47.525447+00', '上古丶白澤夜落', NULL);
INSERT INTO "public"."GuildMembers" VALUES (396947571806830592, '.maolin#0000', 3, '2025-04-20 07:26:34.525005+00', '上古丶太陽燭照', NULL);
INSERT INTO "public"."GuildMembers" VALUES (716659740238807091, 'ouo528#0000', 0, '2025-04-20 07:26:38.84487+00', '上古丶應龍玖墨', NULL);
INSERT INTO "public"."GuildMembers" VALUES (879342799173087252, 'yuu0430#0000', 1, '2025-04-20 07:26:46.24914+00', '上古丶天狐靈蟹', NULL);
INSERT INTO "public"."GuildMembers" VALUES (885552208433782805, 'xhauu193#0000', 1, '2025-04-20 07:26:41.729248+00', '慕意', NULL);
INSERT INTO "public"."GuildMembers" VALUES (942791234483810336, 'ping1752#0000', 1, '2025-04-20 07:26:45.292551+00', '上古丶太陰幽熒', NULL);
INSERT INTO "public"."GuildMembers" VALUES (999711493668999270, 'miya_rio#0000', 0, '2025-04-20 07:26:35.801876+00', '上古丶朱雀梨緒', NULL);
INSERT INTO "public"."GuildMembers" VALUES (419842930627575808, 'tyr5678943#0000', 2, '2025-04-25 14:46:30.358569+00', '上古丶幽夜魂曲', NULL);
INSERT INTO "public"."GuildMembers" VALUES (1364217516666392587, 'xiao_meow#0000', 5, '2025-04-25 14:46:27.190871+00', '縱橫沙場君莫笑', NULL);
INSERT INTO "public"."GuildMembers" VALUES (1365340720327819356, 't0123492#0000', 3, '2025-04-25 15:02:29.191422+00', '墨梓宸', NULL);
INSERT INTO "public"."GuildMembers" VALUES (341591911456571394, 'skr123#0000', 4, '2025-04-25 14:46:29.708908+00', '喬伊陡歌', '2025-04-27 09:06:53.826482+00');
INSERT INTO "public"."GuildMembers" VALUES (528231541466202113, 'mason079733#0000', 3, '2025-04-02 00:03:11.905684+00', '尼羅河芭斯特', '2025-04-27 09:06:58.659864+00');

-- ----------------------------
-- Table structure for GuildTeamMembers
-- ----------------------------
DROP TABLE IF EXISTS "public"."GuildTeamMembers";
CREATE TABLE "public"."GuildTeamMembers" (
  "Id" "pg_catalog"."int4" NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "GuildTeamId" "pg_catalog"."int4" NOT NULL,
  "DiscordMemberId" "pg_catalog"."int8" NOT NULL,
  "Position" "pg_catalog"."int4" NOT NULL
)
;

-- ----------------------------
-- Records of GuildTeamMembers
-- ----------------------------
INSERT INTO "public"."GuildTeamMembers" VALUES (20, 0, 1076134921141244044, 0);
INSERT INTO "public"."GuildTeamMembers" VALUES (32, 8, 857421612281888779, 0);
INSERT INTO "public"."GuildTeamMembers" VALUES (38, 7, 744474458009370644, 3);
INSERT INTO "public"."GuildTeamMembers" VALUES (40, 5, 661916530774245377, 1);
INSERT INTO "public"."GuildTeamMembers" VALUES (42, 10, 909878300632031262, 0);
INSERT INTO "public"."GuildTeamMembers" VALUES (46, 6, 550326920181448710, 5);
INSERT INTO "public"."GuildTeamMembers" VALUES (48, 9, 823391830288629800, 2);
INSERT INTO "public"."GuildTeamMembers" VALUES (50, 8, 272377247938117632, 5);
INSERT INTO "public"."GuildTeamMembers" VALUES (51, 3, 316650845410426893, 4);
INSERT INTO "public"."GuildTeamMembers" VALUES (44, 7, 391561628975497218, 1);
INSERT INTO "public"."GuildTeamMembers" VALUES (13, 8, 982308718484004925, 2);
INSERT INTO "public"."GuildTeamMembers" VALUES (45, 2, 582127945670197256, 7);
INSERT INTO "public"."GuildTeamMembers" VALUES (68, 3, 766938163875938324, 2);
INSERT INTO "public"."GuildTeamMembers" VALUES (71, 1, 1353033269343555598, 7);
INSERT INTO "public"."GuildTeamMembers" VALUES (55, 6, 524557540621680640, 1);
INSERT INTO "public"."GuildTeamMembers" VALUES (54, 7, 520222167481319424, 4);
INSERT INTO "public"."GuildTeamMembers" VALUES (33, 3, 356848603442053130, 1);
INSERT INTO "public"."GuildTeamMembers" VALUES (96, 10, 1365340720327819356, 5);
INSERT INTO "public"."GuildTeamMembers" VALUES (5, 0, 472397644279447552, 5);
INSERT INTO "public"."GuildTeamMembers" VALUES (23, 0, 690261526132686916, 11);
INSERT INTO "public"."GuildTeamMembers" VALUES (34, 0, 1017432363434791034, 12);
INSERT INTO "public"."GuildTeamMembers" VALUES (36, 3, 783351681915158548, 0);
INSERT INTO "public"."GuildTeamMembers" VALUES (35, 0, 409351484854239233, 13);
INSERT INTO "public"."GuildTeamMembers" VALUES (37, 0, 525720558521024514, 15);
INSERT INTO "public"."GuildTeamMembers" VALUES (47, 3, 326695675741995015, 7);
INSERT INTO "public"."GuildTeamMembers" VALUES (61, 0, 418038803018678321, 10);
INSERT INTO "public"."GuildTeamMembers" VALUES (73, 0, 381399468655902720, 7);
INSERT INTO "public"."GuildTeamMembers" VALUES (75, 0, 995160471185408112, 6);
INSERT INTO "public"."GuildTeamMembers" VALUES (78, 0, 1339598641848913980, 8);
INSERT INTO "public"."GuildTeamMembers" VALUES (90, 0, 562270564220272670, 4);
INSERT INTO "public"."GuildTeamMembers" VALUES (92, 0, 1364217516666392587, 3);
INSERT INTO "public"."GuildTeamMembers" VALUES (58, 6, 1308436623456862208, 3);
INSERT INTO "public"."GuildTeamMembers" VALUES (93, 0, 341591911456571394, 2);
INSERT INTO "public"."GuildTeamMembers" VALUES (49, 2, 334291140851269632, 2);
INSERT INTO "public"."GuildTeamMembers" VALUES (60, 3, 528231541466202113, 5);
INSERT INTO "public"."GuildTeamMembers" VALUES (62, 1, 163231110443171840, 1);
INSERT INTO "public"."GuildTeamMembers" VALUES (65, 9, 967483737468186714, 4);
INSERT INTO "public"."GuildTeamMembers" VALUES (3, 2, 501759556544888844, 5);
INSERT INTO "public"."GuildTeamMembers" VALUES (70, 2, 948733226426458162, 1);
INSERT INTO "public"."GuildTeamMembers" VALUES (4, 9, 277859742830034944, 1);
INSERT INTO "public"."GuildTeamMembers" VALUES (41, 7, 315387095130832897, 0);
INSERT INTO "public"."GuildTeamMembers" VALUES (14, 1, 112543801976893440, 2);
INSERT INTO "public"."GuildTeamMembers" VALUES (6, 2, 686879184059891715, 3);
INSERT INTO "public"."GuildTeamMembers" VALUES (66, 2, 355332247504814081, 0);
INSERT INTO "public"."GuildTeamMembers" VALUES (8, 1, 396651117532020746, 5);
INSERT INTO "public"."GuildTeamMembers" VALUES (9, 7, 891856852432863243, 5);
INSERT INTO "public"."GuildTeamMembers" VALUES (64, 1, 352084105657319425, 0);
INSERT INTO "public"."GuildTeamMembers" VALUES (11, 8, 476305034448076811, 3);
INSERT INTO "public"."GuildTeamMembers" VALUES (15, 2, 337976161009139712, 4);
INSERT INTO "public"."GuildTeamMembers" VALUES (17, 6, 472440976758276097, 0);
INSERT INTO "public"."GuildTeamMembers" VALUES (19, 6, 564378682429276180, 2);
INSERT INTO "public"."GuildTeamMembers" VALUES (21, 6, 498868109818593300, 4);
INSERT INTO "public"."GuildTeamMembers" VALUES (22, 9, 824165263272312852, 0);
INSERT INTO "public"."GuildTeamMembers" VALUES (25, 1, 1008084653544046593, 3);
INSERT INTO "public"."GuildTeamMembers" VALUES (26, 8, 558310783516278794, 4);
INSERT INTO "public"."GuildTeamMembers" VALUES (27, 10, 1083333926145232946, 4);
INSERT INTO "public"."GuildTeamMembers" VALUES (29, 7, 557928446559387659, 2);
INSERT INTO "public"."GuildTeamMembers" VALUES (30, 3, 181297590388654080, 3);
INSERT INTO "public"."GuildTeamMembers" VALUES (31, 1, 505686653197746186, 4);
INSERT INTO "public"."GuildTeamMembers" VALUES (74, 10, 247054516237631490, 1);
INSERT INTO "public"."GuildTeamMembers" VALUES (76, 9, 546543160055300127, 5);
INSERT INTO "public"."GuildTeamMembers" VALUES (79, 10, 699094304915980318, 3);
INSERT INTO "public"."GuildTeamMembers" VALUES (80, 5, 396947571806830592, 5);
INSERT INTO "public"."GuildTeamMembers" VALUES (81, 5, 999711493668999270, 4);
INSERT INTO "public"."GuildTeamMembers" VALUES (82, 4, 716659740238807091, 3);
INSERT INTO "public"."GuildTeamMembers" VALUES (83, 10, 885552208433782805, 2);
INSERT INTO "public"."GuildTeamMembers" VALUES (84, 4, 433453802272849920, 4);
INSERT INTO "public"."GuildTeamMembers" VALUES (85, 5, 942791234483810336, 0);
INSERT INTO "public"."GuildTeamMembers" VALUES (86, 4, 879342799173087252, 0);
INSERT INTO "public"."GuildTeamMembers" VALUES (87, 5, 334349689061113856, 2);
INSERT INTO "public"."GuildTeamMembers" VALUES (88, 4, 576804780584861706, 5);
INSERT INTO "public"."GuildTeamMembers" VALUES (89, 5, 574918160197746699, 3);
INSERT INTO "public"."GuildTeamMembers" VALUES (91, 9, 525692851468763156, 3);
INSERT INTO "public"."GuildTeamMembers" VALUES (94, 4, 419842930627575808, 1);

-- ----------------------------
-- Table structure for GuildTeams
-- ----------------------------
DROP TABLE IF EXISTS "public"."GuildTeams";
CREATE TABLE "public"."GuildTeams" (
  "Id" "pg_catalog"."int4" NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "TeamGroupId" "pg_catalog"."int4" NOT NULL,
  "TeamName" "pg_catalog"."text" COLLATE "pg_catalog"."default" NOT NULL,
  "Order" "pg_catalog"."int4"
)
;

-- ----------------------------
-- Records of GuildTeams
-- ----------------------------
INSERT INTO "public"."GuildTeams" VALUES (2, 1, '進攻二隊', 2);
INSERT INTO "public"."GuildTeams" VALUES (3, 1, '進攻三隊', 3);
INSERT INTO "public"."GuildTeams" VALUES (4, 1, '進攻四隊', 4);
INSERT INTO "public"."GuildTeams" VALUES (5, 1, '進攻五隊', 5);
INSERT INTO "public"."GuildTeams" VALUES (0, 0, '', 0);
INSERT INTO "public"."GuildTeams" VALUES (1, 1, '進攻一隊', 1);
INSERT INTO "public"."GuildTeams" VALUES (8, 2, '防守一隊', 3);
INSERT INTO "public"."GuildTeams" VALUES (9, 2, '防守二隊', 4);
INSERT INTO "public"."GuildTeams" VALUES (10, 2, '防守三隊', 5);
INSERT INTO "public"."GuildTeams" VALUES (6, 2, '拆塔隊', 1);
INSERT INTO "public"."GuildTeams" VALUES (7, 2, '物資隊', 2);

-- ----------------------------
-- Table structure for JobSchedules
-- ----------------------------
DROP TABLE IF EXISTS "public"."JobSchedules";
CREATE TABLE "public"."JobSchedules" (
  "Id" "pg_catalog"."int4" NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "JobType" "pg_catalog"."int4" NOT NULL,
  "MessageType" "pg_catalog"."int4",
  "MessageId" "pg_catalog"."int4",
  "Command" "pg_catalog"."text" COLLATE "pg_catalog"."default",
  "CronExpression" "pg_catalog"."text" COLLATE "pg_catalog"."default" NOT NULL,
  "CreatedAt" "pg_catalog"."timestamptz" NOT NULL DEFAULT now(),
  "UpdatedAt" "pg_catalog"."timestamptz" NOT NULL DEFAULT now(),
  "Enabled" "pg_catalog"."bool" NOT NULL
)
;

-- ----------------------------
-- Records of JobSchedules
-- ----------------------------
INSERT INTO "public"."JobSchedules" VALUES (2, 0, 3, 2, NULL, '0 0 19 ? * SAT *', '2025-02-28 23:46:58.02528+00', '2025-02-28 23:46:58.02528+00', 't');
INSERT INTO "public"."JobSchedules" VALUES (3, 0, 3, 3, NULL, '0 50 19 ? * SAT *', '2025-03-01 00:57:30.889883+00', '2025-03-01 00:57:30.889883+00', 't');
INSERT INTO "public"."JobSchedules" VALUES (1, 0, 3, 1, NULL, '0 00 9 ? * SAT *', '2025-02-28 23:41:09.067577+00', '2025-02-28 23:41:09.067577+00', 't');

-- ----------------------------
-- Table structure for MemberStatistics
-- ----------------------------
DROP TABLE IF EXISTS "public"."MemberStatistics";
CREATE TABLE "public"."MemberStatistics" (
  "DiscordId" "pg_catalog"."int8" NOT NULL,
  "TaishanMove" "pg_catalog"."bool" NOT NULL
)
;

-- ----------------------------
-- Records of MemberStatistics
-- ----------------------------
INSERT INTO "public"."MemberStatistics" VALUES (112543801976893440, 't');
INSERT INTO "public"."MemberStatistics" VALUES (163231110443171840, 't');
INSERT INTO "public"."MemberStatistics" VALUES (181297590388654080, 't');
INSERT INTO "public"."MemberStatistics" VALUES (272377247938117632, 't');
INSERT INTO "public"."MemberStatistics" VALUES (315387095130832897, 't');
INSERT INTO "public"."MemberStatistics" VALUES (326695675741995015, 't');
INSERT INTO "public"."MemberStatistics" VALUES (334291140851269632, 't');
INSERT INTO "public"."MemberStatistics" VALUES (337976161009139712, 't');
INSERT INTO "public"."MemberStatistics" VALUES (352084105657319425, 't');
INSERT INTO "public"."MemberStatistics" VALUES (355332247504814081, 't');
INSERT INTO "public"."MemberStatistics" VALUES (391561628975497218, 't');
INSERT INTO "public"."MemberStatistics" VALUES (396651117532020746, 't');
INSERT INTO "public"."MemberStatistics" VALUES (409351484854239233, 't');
INSERT INTO "public"."MemberStatistics" VALUES (472440976758276097, 't');
INSERT INTO "public"."MemberStatistics" VALUES (476305034448076811, 't');
INSERT INTO "public"."MemberStatistics" VALUES (498868109818593300, 't');
INSERT INTO "public"."MemberStatistics" VALUES (501759556544888844, 't');
INSERT INTO "public"."MemberStatistics" VALUES (505686653197746186, 't');
INSERT INTO "public"."MemberStatistics" VALUES (520222167481319424, 't');
INSERT INTO "public"."MemberStatistics" VALUES (524557540621680640, 't');
INSERT INTO "public"."MemberStatistics" VALUES (525720558521024514, 't');
INSERT INTO "public"."MemberStatistics" VALUES (528231541466202113, 't');
INSERT INTO "public"."MemberStatistics" VALUES (550326920181448710, 't');
INSERT INTO "public"."MemberStatistics" VALUES (557928446559387659, 't');
INSERT INTO "public"."MemberStatistics" VALUES (558310783516278794, 't');
INSERT INTO "public"."MemberStatistics" VALUES (564378682429276180, 't');
INSERT INTO "public"."MemberStatistics" VALUES (582127945670197256, 't');
INSERT INTO "public"."MemberStatistics" VALUES (661916530774245377, 't');
INSERT INTO "public"."MemberStatistics" VALUES (766938163875938324, 't');
INSERT INTO "public"."MemberStatistics" VALUES (783351681915158548, 't');
INSERT INTO "public"."MemberStatistics" VALUES (823391830288629800, 't');
INSERT INTO "public"."MemberStatistics" VALUES (824165263272312852, 't');
INSERT INTO "public"."MemberStatistics" VALUES (891856852432863243, 't');
INSERT INTO "public"."MemberStatistics" VALUES (967483737468186714, 't');
INSERT INTO "public"."MemberStatistics" VALUES (982308718484004925, 't');
INSERT INTO "public"."MemberStatistics" VALUES (1008084653544046593, 't');
INSERT INTO "public"."MemberStatistics" VALUES (1017432363434791034, 't');
INSERT INTO "public"."MemberStatistics" VALUES (1076134921141244044, 't');
INSERT INTO "public"."MemberStatistics" VALUES (1308436623456862208, 't');

-- ----------------------------
-- Table structure for MonitoredMessages
-- ----------------------------
DROP TABLE IF EXISTS "public"."MonitoredMessages";
CREATE TABLE "public"."MonitoredMessages" (
  "Id" "pg_catalog"."int4" NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "MessageId" "pg_catalog"."numeric" NOT NULL,
  "ChannelId" "pg_catalog"."numeric" NOT NULL,
  "MessageType" "pg_catalog"."int4" NOT NULL DEFAULT 0
)
;

-- ----------------------------
-- Records of MonitoredMessages
-- ----------------------------
INSERT INTO "public"."MonitoredMessages" VALUES (1, 1345453101758283857, 1345452585103921282, 4);
INSERT INTO "public"."MonitoredMessages" VALUES (2, 1345456906117972059, 1345452585103921282, 4);
INSERT INTO "public"."MonitoredMessages" VALUES (3, 1345496997616025613, 1345452585103921282, 4);
INSERT INTO "public"."MonitoredMessages" VALUES (4, 1348726471186714655, 1348231963898679296, 5);

-- ----------------------------
-- Table structure for OneLineBonds
-- ----------------------------
DROP TABLE IF EXISTS "public"."OneLineBonds";
CREATE TABLE "public"."OneLineBonds" (
  "BondId" "pg_catalog"."int4" NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "DiscordId" "pg_catalog"."int8" NOT NULL,
  "PartnerId" "pg_catalog"."int8",
  "PartnerName" "pg_catalog"."text" COLLATE "pg_catalog"."default" NOT NULL,
  "UpdateTime" "pg_catalog"."timestamptz" NOT NULL,
  "MemberName" "pg_catalog"."text" COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text
)
;

-- ----------------------------
-- Records of OneLineBonds
-- ----------------------------
INSERT INTO "public"."OneLineBonds" VALUES (31, 112543801976893440, 1008084653544046593, '夫君威震八方', '2025-04-02 15:27:50.753195+00', '夫人傾國傾城');
INSERT INTO "public"."OneLineBonds" VALUES (32, 163231110443171840, 564378682429276180, '林栖', '2025-04-02 15:27:58.627103+00', '花火繚亂');
INSERT INTO "public"."OneLineBonds" VALUES (34, 326695675741995015, 964032153291735111, '梨嫣', '2025-04-02 15:28:50.076621+00', '我老公');
INSERT INTO "public"."OneLineBonds" VALUES (35, 337976161009139712, 528231541466202113, '尼羅河芭斯特', '2025-04-02 15:30:42.718054+00', '瀀初');
INSERT INTO "public"."OneLineBonds" VALUES (36, 337976161009139712, 396651117532020746, '百里獨行丶', '2025-04-02 15:30:47.607541+00', '瀀初');
INSERT INTO "public"."OneLineBonds" VALUES (37, 337976161009139712, 334291140851269632, '花語焉', '2025-04-02 15:31:04.460303+00', '瀀初');
INSERT INTO "public"."OneLineBonds" VALUES (38, 337976161009139712, 181297590388654080, '擒無邊光斷天命', '2025-04-02 15:31:21.344234+00', '瀀初');
INSERT INTO "public"."OneLineBonds" VALUES (39, 505686653197746186, 396651117532020746, '百里獨行丶', '2025-04-02 15:39:13.38849+00', '小貓兒');
INSERT INTO "public"."OneLineBonds" VALUES (40, 356848603442053130, 783351681915158548, '琳琅', '2025-04-02 15:39:51.912007+00', '艮嶽');
INSERT INTO "public"."OneLineBonds" VALUES (41, 982308718484004925, 476305034448076811, '蹤影', '2025-04-02 15:40:23.879738+00', '逸筱菲');
INSERT INTO "public"."OneLineBonds" VALUES (42, 1008084653544046593, 524557540621680640, '藥入花眠鎖夜夢', '2025-04-02 21:23:53.119483+00', '夫君威震八方');
INSERT INTO "public"."OneLineBonds" VALUES (43, 337976161009139712, 352084105657319425, '襄逸', '2025-04-02 21:24:42.550586+00', '瀀初');
INSERT INTO "public"."OneLineBonds" VALUES (44, 528231541466202113, 396651117532020746, '百里獨行丶', '2025-04-02 21:25:04.344704+00', '尼羅河芭斯特');
INSERT INTO "public"."OneLineBonds" VALUES (45, 528231541466202113, 316650845410426893, '蘇宇豪', '2025-04-02 21:25:12.157615+00', '尼羅河芭斯特');
INSERT INTO "public"."OneLineBonds" VALUES (46, 528231541466202113, 505686653197746186, '小貓兒', '2025-04-02 21:25:44.261196+00', '尼羅河芭斯特');
INSERT INTO "public"."OneLineBonds" VALUES (47, 783351681915158548, 501759556544888844, '瀧雨', '2025-04-02 21:25:58.982783+00', '琳琅');
INSERT INTO "public"."OneLineBonds" VALUES (49, 1017432363434791034, 1076134921141244044, '海棠微雨梨花雪', '2025-04-02 21:26:44.415228+00', '花雨紛飛陌相思');
INSERT INTO "public"."OneLineBonds" VALUES (50, 472440976758276097, 472397644279447552, '夜小伊', '2025-04-02 21:27:08.205799+00', '墨梓璿');
INSERT INTO "public"."OneLineBonds" VALUES (51, 550326920181448710, 564378682429276180, '林栖', '2025-04-02 21:27:49.104773+00', '三十歲美艷后媽');
INSERT INTO "public"."OneLineBonds" VALUES (52, 418038803018678321, 476305034448076811, '蹤影', '2025-04-02 21:32:31.24232+00', '壹柒伍');
INSERT INTO "public"."OneLineBonds" VALUES (53, 476305034448076811, 857421612281888779, '爾冬寬寬', '2025-04-03 07:42:58.730809+00', '蹤影');
INSERT INTO "public"."OneLineBonds" VALUES (54, 1008084653544046593, 352084105657319425, '襄逸', '2025-04-05 10:41:46.948244+00', '夫君威震八方');
INSERT INTO "public"."OneLineBonds" VALUES (55, 472440976758276097, 967483737468186714, '思欲返宸', '2025-04-05 15:34:02.926911+00', '墨梓璿');
INSERT INTO "public"."OneLineBonds" VALUES (56, 1008084653544046593, 181297590388654080, '擒無邊光斷天命', '2025-04-16 01:54:52.09286+00', '夫君威震八方');

-- ----------------------------
-- Table structure for RoleMagicPacts
-- ----------------------------
DROP TABLE IF EXISTS "public"."RoleMagicPacts";
CREATE TABLE "public"."RoleMagicPacts" (
  "Id" "pg_catalog"."int4" NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "DiscordChannelId" "pg_catalog"."numeric" NOT NULL,
  "MonitoredMessageId" "pg_catalog"."numeric" NOT NULL,
  "Emoji" "pg_catalog"."text" COLLATE "pg_catalog"."default",
  "DiscordRoleId" "pg_catalog"."numeric" NOT NULL
)
;

-- ----------------------------
-- Records of RoleMagicPacts
-- ----------------------------
INSERT INTO "public"."RoleMagicPacts" VALUES (1, 1345452585103921282, 1345453101758283857, '🍎', 1343254054679351356);
INSERT INTO "public"."RoleMagicPacts" VALUES (2, 1345452585103921282, 1345453101758283857, '🍏', 1343257439134421033);
INSERT INTO "public"."RoleMagicPacts" VALUES (3, 1345452585103921282, 1345453101758283857, '🌽', 1344000928537251851);
INSERT INTO "public"."RoleMagicPacts" VALUES (4, 1345452585103921282, 1345453101758283857, '🍐', 1343259625038020761);
INSERT INTO "public"."RoleMagicPacts" VALUES (5, 1345452585103921282, 1345453101758283857, '🍊', 1343259151651962963);
INSERT INTO "public"."RoleMagicPacts" VALUES (6, 1345452585103921282, 1345453101758283857, '🍑', 1343948660731281439);
INSERT INTO "public"."RoleMagicPacts" VALUES (7, 1345452585103921282, 1345453101758283857, '🍋', 1343260172524585010);
INSERT INTO "public"."RoleMagicPacts" VALUES (8, 1345452585103921282, 1345453101758283857, '🥭', 1343949670896111627);
INSERT INTO "public"."RoleMagicPacts" VALUES (9, 1345452585103921282, 1345453101758283857, '🍍', 1343949154367307868);
INSERT INTO "public"."RoleMagicPacts" VALUES (10, 1345452585103921282, 1345453101758283857, '🍌', 1343258592572215378);
INSERT INTO "public"."RoleMagicPacts" VALUES (11, 1345452585103921282, 1345453101758283857, '🥥', 1343949664117985290);
INSERT INTO "public"."RoleMagicPacts" VALUES (12, 1345452585103921282, 1345453101758283857, '🥝', 1343950161407115264);
INSERT INTO "public"."RoleMagicPacts" VALUES (13, 1345452585103921282, 1345453101758283857, '🍉', 1343258517280129055);
INSERT INTO "public"."RoleMagicPacts" VALUES (14, 1345452585103921282, 1345453101758283857, '🍇', 1343259496713027585);
INSERT INTO "public"."RoleMagicPacts" VALUES (15, 1345452585103921282, 1345453101758283857, '🍓', 1343258841671929946);
INSERT INTO "public"."RoleMagicPacts" VALUES (16, 1345452585103921282, 1345453101758283857, '🍅', 1343952020083576842);
INSERT INTO "public"."RoleMagicPacts" VALUES (17, 1345452585103921282, 1345453101758283857, '🍆', 1343952874278879232);
INSERT INTO "public"."RoleMagicPacts" VALUES (18, 1345452585103921282, 1345453101758283857, '🥑', 1343953205897465977);
INSERT INTO "public"."RoleMagicPacts" VALUES (19, 1345452585103921282, 1345453101758283857, '🍈', 1343256277538574438);
INSERT INTO "public"."RoleMagicPacts" VALUES (20, 1345452585103921282, 1345453101758283857, '🍒', 1343258062106136586);
INSERT INTO "public"."RoleMagicPacts" VALUES (21, 1345452585103921282, 1345456906117972059, '🌶️', 1344351623060914216);
INSERT INTO "public"."RoleMagicPacts" VALUES (22, 1345452585103921282, 1345456906117972059, '🥕', 1344358121572667433);
INSERT INTO "public"."RoleMagicPacts" VALUES (23, 1345452585103921282, 1345456906117972059, '🥒', 1344358499207090186);
INSERT INTO "public"."RoleMagicPacts" VALUES (24, 1345452585103921282, 1345456906117972059, '🥦', 1344358873225625600);
INSERT INTO "public"."RoleMagicPacts" VALUES (25, 1345452585103921282, 1345456906117972059, '🥬', 1344359212633034812);
INSERT INTO "public"."RoleMagicPacts" VALUES (26, 1345452585103921282, 1345456906117972059, '🐱', 1344367811945828494);
INSERT INTO "public"."RoleMagicPacts" VALUES (27, 1345452585103921282, 1345456906117972059, '🎂', 1344373261336580306);
INSERT INTO "public"."RoleMagicPacts" VALUES (28, 1345452585103921282, 1345456906117972059, '🧄', 1344373524944519219);
INSERT INTO "public"."RoleMagicPacts" VALUES (29, 1345452585103921282, 1345496997616025613, '🗡️', 1345481853209149450);
INSERT INTO "public"."RoleMagicPacts" VALUES (31, 1345452585103921282, 1345496997616025613, '🏹', 1345484264552136734);
INSERT INTO "public"."RoleMagicPacts" VALUES (30, 1345452585103921282, 1345496997616025613, '🪓', 1345483299119825001);
INSERT INTO "public"."RoleMagicPacts" VALUES (32, 1345452585103921282, 1345496997616025613, '🕵️', 1348626031669411872);

-- ----------------------------
-- Table structure for StatisticsConfigs
-- ----------------------------
DROP TABLE IF EXISTS "public"."StatisticsConfigs";
CREATE TABLE "public"."StatisticsConfigs" (
  "Id" "pg_catalog"."int4" NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "Emoji" "pg_catalog"."text" COLLATE "pg_catalog"."default" NOT NULL,
  "StatisticsType" "pg_catalog"."int4" NOT NULL,
  "StatisticsName" "pg_catalog"."text" COLLATE "pg_catalog"."default" NOT NULL DEFAULT ''::text
)
;

-- ----------------------------
-- Records of StatisticsConfigs
-- ----------------------------
INSERT INTO "public"."StatisticsConfigs" VALUES (1, '📿', 10, '泰山移');

-- ----------------------------
-- Table structure for TeamGroups
-- ----------------------------
DROP TABLE IF EXISTS "public"."TeamGroups";
CREATE TABLE "public"."TeamGroups" (
  "Id" "pg_catalog"."int4" NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "GroupName" "pg_catalog"."text" COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of TeamGroups
-- ----------------------------
INSERT INTO "public"."TeamGroups" VALUES (1, '一團');
INSERT INTO "public"."TeamGroups" VALUES (2, '二團');
INSERT INTO "public"."TeamGroups" VALUES (0, '請假名單');

-- ----------------------------
-- Primary Key structure for table __EFMigrationsHistory
-- ----------------------------
ALTER TABLE "public"."__EFMigrationsHistory" ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");

-- ----------------------------
-- Primary Key structure for table DiscordChannels
-- ----------------------------
ALTER TABLE "public"."DiscordChannels" ADD CONSTRAINT "PK_DiscordChannels" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for DiscordMessages
-- ----------------------------
SELECT setval('"public"."Messages_Id_seq"', 4, true);

-- ----------------------------
-- Primary Key structure for table DiscordMessages
-- ----------------------------
ALTER TABLE "public"."DiscordMessages" ADD CONSTRAINT "PK_DiscordMessages" PRIMARY KEY ("Id");

-- ----------------------------
-- Primary Key structure for table DiscordRoles
-- ----------------------------
ALTER TABLE "public"."DiscordRoles" ADD CONSTRAINT "PK_DiscordRoles" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for GuildMembers
-- ----------------------------
SELECT setval('"public"."GuildMembers_DiscordId_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table GuildMembers
-- ----------------------------
ALTER TABLE "public"."GuildMembers" ADD CONSTRAINT "PK_GuildMembers" PRIMARY KEY ("DiscordId");

-- ----------------------------
-- Auto increment value for GuildTeamMembers
-- ----------------------------
SELECT setval('"public"."GuildTeamMembers_Id_seq"', 96, true);

-- ----------------------------
-- Indexes structure for table GuildTeamMembers
-- ----------------------------
CREATE INDEX "IX_GuildTeamMembers_GuildTeamId" ON "public"."GuildTeamMembers" USING btree (
  "GuildTeamId" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table GuildTeamMembers
-- ----------------------------
ALTER TABLE "public"."GuildTeamMembers" ADD CONSTRAINT "PK_GuildTeamMembers" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for GuildTeams
-- ----------------------------
SELECT setval('"public"."GuildTeams_Id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table GuildTeams
-- ----------------------------
CREATE INDEX "IX_GuildTeams_TeamGroupId" ON "public"."GuildTeams" USING btree (
  "TeamGroupId" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table GuildTeams
-- ----------------------------
ALTER TABLE "public"."GuildTeams" ADD CONSTRAINT "PK_GuildTeams" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for JobSchedules
-- ----------------------------
SELECT setval('"public"."JobSchedules_Id_seq"', 8, true);

-- ----------------------------
-- Primary Key structure for table JobSchedules
-- ----------------------------
ALTER TABLE "public"."JobSchedules" ADD CONSTRAINT "PK_JobSchedules" PRIMARY KEY ("Id");

-- ----------------------------
-- Primary Key structure for table MemberStatistics
-- ----------------------------
ALTER TABLE "public"."MemberStatistics" ADD CONSTRAINT "PK_MemberStatistics" PRIMARY KEY ("DiscordId");

-- ----------------------------
-- Auto increment value for MonitoredMessages
-- ----------------------------
SELECT setval('"public"."MonitoredMessages_Id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table MonitoredMessages
-- ----------------------------
CREATE UNIQUE INDEX "IX_MonitoredMessages_MessageId" ON "public"."MonitoredMessages" USING btree (
  "MessageId" "pg_catalog"."numeric_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table MonitoredMessages
-- ----------------------------
ALTER TABLE "public"."MonitoredMessages" ADD CONSTRAINT "AK_MonitoredMessages_MessageId" UNIQUE ("MessageId");

-- ----------------------------
-- Primary Key structure for table MonitoredMessages
-- ----------------------------
ALTER TABLE "public"."MonitoredMessages" ADD CONSTRAINT "PK_MonitoredMessages" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for OneLineBonds
-- ----------------------------
SELECT setval('"public"."OneLineBonds_BondId_seq"', 57, true);

-- ----------------------------
-- Indexes structure for table OneLineBonds
-- ----------------------------
CREATE INDEX "IX_OneLineBonds_DiscordId" ON "public"."OneLineBonds" USING btree (
  "DiscordId" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table OneLineBonds
-- ----------------------------
ALTER TABLE "public"."OneLineBonds" ADD CONSTRAINT "PK_OneLineBonds" PRIMARY KEY ("BondId");

-- ----------------------------
-- Auto increment value for RoleMagicPacts
-- ----------------------------
SELECT setval('"public"."RoleMagicPacts_Id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table RoleMagicPacts
-- ----------------------------
CREATE INDEX "IX_RoleMagicPacts_DiscordChannelId" ON "public"."RoleMagicPacts" USING btree (
  "DiscordChannelId" "pg_catalog"."numeric_ops" ASC NULLS LAST
);
CREATE INDEX "IX_RoleMagicPacts_DiscordRoleId" ON "public"."RoleMagicPacts" USING btree (
  "DiscordRoleId" "pg_catalog"."numeric_ops" ASC NULLS LAST
);
CREATE INDEX "IX_RoleMagicPacts_MonitoredMessageId" ON "public"."RoleMagicPacts" USING btree (
  "MonitoredMessageId" "pg_catalog"."numeric_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table RoleMagicPacts
-- ----------------------------
ALTER TABLE "public"."RoleMagicPacts" ADD CONSTRAINT "PK_RoleMagicPacts" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for StatisticsConfigs
-- ----------------------------
SELECT setval('"public"."StatisticsConfigs_Id_seq"', 1, true);

-- ----------------------------
-- Indexes structure for table StatisticsConfigs
-- ----------------------------
CREATE UNIQUE INDEX "IX_StatisticsConfigs_Emoji" ON "public"."StatisticsConfigs" USING btree (
  "Emoji" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table StatisticsConfigs
-- ----------------------------
ALTER TABLE "public"."StatisticsConfigs" ADD CONSTRAINT "PK_StatisticsConfigs" PRIMARY KEY ("Id");

-- ----------------------------
-- Auto increment value for TeamGroups
-- ----------------------------
SELECT setval('"public"."TeamGroups_Id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table TeamGroups
-- ----------------------------
ALTER TABLE "public"."TeamGroups" ADD CONSTRAINT "PK_TeamGroups" PRIMARY KEY ("Id");

-- ----------------------------
-- Foreign Keys structure for table GuildTeamMembers
-- ----------------------------
ALTER TABLE "public"."GuildTeamMembers" ADD CONSTRAINT "FK_GuildTeamMembers_GuildTeams_GuildTeamId" FOREIGN KEY ("GuildTeamId") REFERENCES "public"."GuildTeams" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table GuildTeams
-- ----------------------------
ALTER TABLE "public"."GuildTeams" ADD CONSTRAINT "FK_GuildTeams_TeamGroups_TeamGroupId" FOREIGN KEY ("TeamGroupId") REFERENCES "public"."TeamGroups" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table MemberStatistics
-- ----------------------------
ALTER TABLE "public"."MemberStatistics" ADD CONSTRAINT "FK_MemberStatistics_GuildMembers_DiscordId" FOREIGN KEY ("DiscordId") REFERENCES "public"."GuildMembers" ("DiscordId") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table OneLineBonds
-- ----------------------------
ALTER TABLE "public"."OneLineBonds" ADD CONSTRAINT "FK_OneLineBonds_GuildMembers_DiscordId" FOREIGN KEY ("DiscordId") REFERENCES "public"."GuildMembers" ("DiscordId") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table RoleMagicPacts
-- ----------------------------
ALTER TABLE "public"."RoleMagicPacts" ADD CONSTRAINT "FK_RoleMagicPacts_DiscordChannels_DiscordChannelId" FOREIGN KEY ("DiscordChannelId") REFERENCES "public"."DiscordChannels" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "public"."RoleMagicPacts" ADD CONSTRAINT "FK_RoleMagicPacts_DiscordRoles_DiscordRoleId" FOREIGN KEY ("DiscordRoleId") REFERENCES "public"."DiscordRoles" ("Id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "public"."RoleMagicPacts" ADD CONSTRAINT "FK_RoleMagicPacts_MonitoredMessages_MonitoredMessageId" FOREIGN KEY ("MonitoredMessageId") REFERENCES "public"."MonitoredMessages" ("MessageId") ON DELETE CASCADE ON UPDATE NO ACTION;
