name: Deploy Discord Bot

on:
  push:
    branches:
      - dev

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore DiscordBot/DiscordBot/DiscordBot.sln  # 確保指定解決方案文件

      - name: Build project
        run: dotnet build DiscordBot/DiscordBot/DiscordBot.sln --configuration Release  # 確保指定解決方案文件

      - name: Run Discord Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORDBOT_TOKEN }}  # 設置環境變數
        run: dotnet run --project DiscordBot/DiscordBot/DiscordBot/DiscordBot.csproj  # 確保專案路徑正確
